services:
  postgres-core:
    image: postgres:16
    environment:
      POSTGRES_USER: ods
      POSTGRES_PASSWORD: ods
      POSTGRES_DB: ods_core
    ports: ["5433:5432"]
    volumes:
      - pg_core:/var/lib/postgresql/data

  postgres-node:
    image: postgres:16
    environment:
      POSTGRES_USER: ods
      POSTGRES_PASSWORD: ods
      POSTGRES_DB: ods_node
    ports: ["5434:5432"]
    volumes:
      - pg_node:/var/lib/postgresql/data

volumes:
  pg_core:
  pg_node:
